---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello hostname
      debug:
        msg="{{ ansible_facts.hostname }}"
    - name: cmd
      ansible.builtin.command: ls -al ~/
      register: _cmd
    - name: debug mount
      debug:
        msg="{{ _cmd }}"
