---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Hello hostname
      debug:
        msg="{{ ansible_facts.hostname }}"
    - name: Sleep for 30 seconds and continue with play
      wait_for:
        timeout: 30
      delegate_to: localhost
    - name: cmd
      ansible.builtin.command: whoami
      register: _cmd
    - name: debug cmd
      debug:
        msg="{{ _cmd }}"
    - name: debug e_vars_1
      debug:
        msg="{{ e_vars_1 }}"
    - name: debug e_vars_2
      debug:
        msg="{{ e_vars_2 }}"
